spring.application.name=serviceportal

server.port=${PORT:8080}

spring.datasource.url=jdbc:${MYSQL_PUBLIC_URL:mysql://localhost:3307/serviceportal}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:mySecretKeyMySecretKeyMySecretKey123456}
app.jwt.expiration-ms=86400000

app.admin.secret-key=${ADMIN_SECRET:AdminSecret123}
app.base-url=${APP_BASE_URL:http://localhost:8080}

