spring.application.name=serviceportal

server.port=${PORT:8080}

spring.datasource.url=jdbc:${MYSQL_PUBLIC_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=mySecretKeyMySecretKeyMySecretKey123456
app.jwt.expiration-ms=86400000
